### ISSUE TITLE
Update example to use newer version of cake

### ISSUE THREAD

**Issue by devlead** [cake-build/example#4]
Currently [package.config](https://github.com/cake-build/example/blob/master/tools/packages.config) uses 0.5.2.

**Comment by gep13** [comment]
Yes, I think this is great idea.  I also think that we need to add this to our release process, so we update this example repo every time we release a new version of Cake

**Comment by devlead** [comment]
@gep13 I'll fix today, agree then we should look at including as part of the release process.

**Comment by patriksvensson** [comment]
We could also always get the latest version of Cake and make sure the build pass as a part of our Bakery build.

**Comment by gep13** [comment]
@patriksvensson that would also work, assuming that is what we want the example script to do.  Since users are going to use this as the basis of their scripts going forward, do we want the default to always be to pull the latest?  Personally, I think this is a good idea, but just throwing the question out there :smile:

**Comment by patriksvensson** [comment]
@gep13 Hmm, yeah, you got a point. Let's start by adding it to our release process as you and @devlead suggested and take it from there.

**Comment by gep13** [comment]
I have just updated the process steps to include updating this repository on a Cake release as well.

**Comment by devlead** [comment]
@gep13 Excellent :+1:
